# Generated by Django 3.2.4 on 2021-07-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_alter_snippet_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='copy_count',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
