# Generated by Django 3.2.4 on 2021-07-01 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_alter_tags_name'),
        ('snippets', '0003_snippet_copy_count'),
    ]

    operations = [
    ]
